---

- user:
    name: cms
    shell: /bin/bash

- name: Install basic softwares
  apt: name={{ item }}  state=latest update_cache=yes
  with_items:
    - binutils
    - build-essential
    - curl
    - git
    - git-core
    - libbz2-dev
    - libev-dev
    - libffi-dev
    - libgdbm-dev
    - libjpeg8-dev
    - libpcre3-dev
    - libpq-dev
    - libssl-dev
    - libssl-dev
    - libwebp-dev
    - nginx
    - python
    - python-dev
    - python-pip

- name: Create directory
  file: path=/opt/4HBYTES state=directory


- name: Install virtualenv
  pip: name=virtualenv
  
- name: Clone cms
  git:
    repo: https://github.com/4HBYTES/museum-cms.git
    dest: /opt/4HBYTES/cms
    version: "{{ cms_branch }}"
    accept_hostkey: yes
  register: gitclone

- name: Stop service and clean
  shell: systemctl stop cms.service ; find . -name "*.pyc" -exec rm -rf {} \;
  args:
    chdir: /opt/4HBYTES/cms
  notify: cms-restart
  when: gitclone.changed

- name: Create the virtualenv
  pip: virtualenv_command=virtualenv virtualenv=/opt/4HBYTES/cms/env requirements=/opt/4HBYTES/cms/requirements.txt
  notify: cms-restart
  when: gitclone.changed

- name: systemd configuration cms
  template: src=cms.service.j2 dest=/etc/systemd/system/cms.service

- name: cms-restart
  systemd:
    enabled: yes
    daemon_reload: yes
    name: cms
