---

- name: Install basic softwares
  apt: name={{ item }}  state=latest
  with_items:
    - nginx
  
- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: nginx-reload
  
- name: mime types
  template: src=mime.types.j2 dest=/etc/nginx/mime.types
  notify: nginx-reload
